### ISSUE TITLE
Python import not working

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontcrunch#12]
```
$ sudo pip install --upgrade git+https://github.com/googlefonts/fontcrunch.git;
...
$ python;
>>> from fontcrunch import fontcrunch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fontcrunch/__init__.py", line 1, in <module>
    from .fontcrunch import optimize
  File "/usr/local/lib/python2.7/site-packages/fontcrunch/fontcrunch.py", line 26, in <module>
    from . import quadopt
ImportError: cannot import name quadopt
>>>
```

**Comment by khaledhosny** [comment]
I think installing through pip is broken.

**Comment by davelab6** [comment]
Thank you @khaledhosny ! :)
